# frontend-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend # Assurez-vous que le nom de l'image correspond à celui que vous avez donné lors de la construction du conteneur
        ports:
        - containerPort: 4200  # Port sur lequel votre application écoute à l'intérieur du conteneur

---
# frontend-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: webapp
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Port sur lequel le service sera exposé à l'extérieur
      targetPort: 4200  # Port sur lequel le conteneur écoute à l'intérieur
  type: LoadBalancer  # Changez en NodePort ou ClusterIP selon vos besoins
